version: "3"

services:
  node:
    image: node:16
    container_name: trybesmith
    tty: true
    stdin_open: true
    command: sh -c "npm install && npm start"
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      MYSQL_DATABASE: Trybesmith

  db:
    container_name: trybesmith_db
    image: mysql:8.0.26
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - ./:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: trybesmith_net


